### ISSUE TITLE
populate_db crashs when run on an existing db

### ISSUE THREAD

**Issue by liangcai2012** [liangcai2012/savant-torrey-ranch#26]
Currently populate_db cannot run on an existing db. The main reason is the known_exchs is initialized as empty, rather than reading from database. So when it adds a new company, it tries to insert the exchange and causes a crash.

**Comment by loki900718** [comment]
Yes let me fix this tonight.

**Comment by liangcai-davis** [comment]
Thanks

**Comment by loki900718** [comment]
fixed
