### ISSUE TITLE
Fetcher wont create subfolder 

### ISSUE THREAD

**Issue by liangcai2012** [liangcai2012/savant-torrey-ranch#27]
The current fetcher does not automatically create the subfolder using date. For example:
python fetch_attick.py get LC 20150522

this command will not generate the output file unless the folder 20150522 is manually created.

**Comment by loki900718** [comment]
I don't have this problem. Can you recheck this issue on your local copy?

**Comment by liangcai2012** [comment]
The issue was no longer found.
