### ISSUE TITLE
Code hangup in onTickHistoryOverload() in fetcher

### ISSUE THREAD

**Issue by liangcai2012** [liangcai2012/savant-torrey-ranch#28]
This happens when I run 
python fetch_attick.py get AAPL 20150522

Server halt after printing: [java] Overloaded: 100000

I did some debugging and found there is a json parsing exception when you try to access lastRequest.get("date"), I printed lastRequest and did not see date field:
{"beginDateTime":"20150522090000","symbol":"AAPL","endDateTime":"20150522100000"}

**Comment by loki900718** [comment]
fixed

**Comment by liangcai2012** [comment]
you probably have not merged your fix to master

**Comment by loki900718** [comment]
Should be good now.
