### ISSUE TITLE
fetch_attick broken after using config for PORT

### ISSUE THREAD

**Issue by liangcai2012** [liangcai2012/savant-torrey-ranch#32]
See output:
raceback (most recent call last):
  File "fetch_attick.py", line 65, in <module>
    main()
  File "fetch_attick.py", line 62, in main
    args.func(args)
  File "fetch_attick.py", line 32, in get_data
    caller = FetcherCaller(json_request)
  File "fetch_attick.py", line 12, in **init**
    self.connect()
  File "fetch_attick.py", line 17, in connect
    self.socket.connect((settings.FETCHER_HOST, self.FETCHER_PORT))
AttributeError: FetcherCaller instance has no attribute 'FETCHER_PORT'

**Comment by loki900718** [comment]
fixed

**Comment by liangcai2012** [comment]
You forgot to merge the fix to master again.

**Comment by loki900718** [comment]
I think I did. I just checked the master branch and it looks good.

self.socket.connect((settings.FETCHER_HOST,int(settings.FETCHER_PORT)))

**Comment by liangcai-davis** [comment]
That was done by me.
