### ISSUE TITLE
[IPO] read IPO scroop rating

### ISSUE THREAD

**Issue by liangcai2012** [liangcai2012/savant-torrey-ranch#54]
Give a symbol, find the IPO scooping rating from iposcoop csv file.

**Comment by wholmes123** [comment]
This is done and checked-in code. One problem is that I didn't found 'out'
folder under savant, so the code is based on 'iposcoop.csv' is under the
same folder with the code itself. I will change the path in code after we
confirm the 'iposcoop.csv' file path.

Thanks
Chuan

2015-07-19 6:32 GMT+08:00 liangcai2012 notifications@github.com:

**Comment by liangcai2012** [comment]
out folder is out side of savant.

savant-torrey-ranch is the home folder

out is the data for all data. We dont push any content in it to git
savant is the src folder. it is pushed to git.

**Comment by wholmes123** [comment]
ok, then I will just change the path to "'../../../out/iposcoop.csv'"
Thanks
Chuan

2015-07-19 12:11 GMT-07:00 liangcai2012 notifications@github.com:
